name: Takipci Robotu

on:
  workflow_dispatch:

jobs:
  veri-cek:
    runs-on: ubuntu-latest
    steps:
      - name: Dosyalari Al
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Araclari Yukle
        run: pip install -r requirements.txt

      - name: Kodu Calistir
        env:
          IG_KULLANICI_ADI: ${{ secrets.IG_KULLANICI_ADI }}
          IG_SIFRE: ${{ secrets.IG_SIFRE }}
        run: python main.py
